name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 仅在 push tag 时触发
  workflow_dispatch:

# 为整个工作流设置默认权限
permissions:
  contents: write  # 关键：授予创建 Release 和上传资产的权限

jobs:
  build-windows:
    runs-on: windows-latest

    # 也可以仅在特定作业中设置权限（二选一）
    # permissions:
    #   contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史记录和标签，有助于某些 Actions 识别 tag

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: |
          flutter clean
          flutter build windows --release --dart-define=CMAKE_BUILD_TYPE=Release

      - name: Find Windows exe
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path build\windows -Recurse -Filter *.exe | Where-Object { $_.Name -notlike "*flutter*" } | Select-Object -First 1
          if (-not $exe) {
            Write-Error "No exe found. Build might have failed."
            exit 1
          }
          echo "Found exe at $($exe.FullName)"
          echo "exe_path=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create zip
        run: |
          $zipDir = "build\windows\release_zip"
          New-Item -ItemType Directory -Path $zipDir -Force
          Copy-Item -Path "${{ steps.find_exe.outputs.exe_path }}" -Destination $zipDir
          $exeName = [System.IO.Path]::GetFileName("${{ steps.find_exe.outputs.exe_path }}")
          Compress-Archive -Path "$zipDir\$exeName" -DestinationPath "build\flutter_windows_app.zip" -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
          tag_name: ${{ github.ref_name }}  # 明确指定标签名称
        # env 部分通常可省略，因为默认使用 GITHUB_TOKEN
        # 但如果需要，也可以显式设置：
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
