name: Build Windows Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"
          architecture: x64

      # 3. 启用 Windows 桌面
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # 4. 获取依赖
      - name: Get Flutter dependencies
        run: flutter pub get

      # 5. 打包 Windows Release
      - name: Build Windows Release
        run: flutter build windows --release

      # 6. 压缩 exe 和依赖文件
      - name: Compress Release
        run: |
          $output = "build/flutter_windows_app.zip"
          if (Test-Path $output) { Remove-Item $output }
          Compress-Archive -Path build/windows/x64/Release/* -DestinationPath $output
          Write-Host "Archive created at $output"

      # 7. 创建 GitHub Release（如果 tag 对应的 Release 不存在）
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name != '' && github.ref_name || 'v1.0.0' }}
          release_name: Release ${{ github.ref_name != '' && github.ref_name || 'v1.0.0' }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. 上传压缩包到 Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
