name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 只有打 tag 才触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          channel: stable
          architecture: x64

      # 3. 启用 Windows Desktop 支持
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # 4. 安装依赖
      - name: Get dependencies
        run: flutter pub get

      # 5. 构建 Windows Release
      - name: Build Windows Release
        run: flutter build windows --release

      # 6. 列出 build/windows 目录，确认生成文件
      - name: List build/windows directory
        run: Get-ChildItem -Path build/windows -Recurse

      # 7. 压缩 exe 文件
      - name: Zip Windows build
        run: |
          $srcPath = "build/windows/runner/Release"
          if (Test-Path $srcPath) {
            Write-Host "Found build output at $srcPath"
            mkdir build/windows/release_zip
            Copy-Item -Path "$srcPath/*" -Destination build/windows/release_zip -Recurse
            Compress-Archive -Path build/windows/release_zip/* -DestinationPath build/flutter_windows_app.zip
            Write-Host "Zip created at build/flutter_windows_app.zip"
          } else {
            Write-Error "$srcPath does not exist. Build might have failed."
            exit 1
          }

      # 8. 上传到 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
