name: Build Windows Release

on:
  push:
    tags:
      - 'v*'   # 只有打 tag 才触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"
          architecture: x64

      # 3. Enable Windows desktop
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      # 4. Get dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # 5. Build Windows release
      - name: Build Windows release
        run: flutter build windows --release

      # 6. 查看 build/windows 目录
      - name: List build/windows directory
        run: Get-ChildItem -Path build/windows -Recurse

      # 7. 压缩 exe 文件和相关依赖
      - name: Zip Windows build
        run: |
          mkdir build/windows/release_zip
          Copy-Item -Path build/windows/runner/Release/* -Destination build/windows/release_zip -Recurse
          Compress-Archive -Path build/windows/release_zip/* -DestinationPath build/flutter_windows_app.zip

      # 8. 上传到 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
