name: Build Windows

on:
  push:
    branches:
      - main   # 当 main 分支有 push 时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows exe
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: build/windows/runner/Release/*.exe