name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 只在打 tag 时触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"
          architecture: x64

      # 3. 启用 Windows Desktop 支持
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # 4. 获取依赖
      - name: Get dependencies
        run: flutter pub get

      # 5. 构建 Windows release
      - name: Build Windows Release
        run: flutter build windows --release

      # 6. 调试：列出 build/windows 内容（可选）
      - name: List build/windows
        run: dir build/windows /s

      # 7. 压缩 Release 文件夹
      - name: Prepare zip
        run: |
          mkdir build/windows/release_zip
          Copy-Item -Path build/windows/runner/Release/* -Destination build/windows/release_zip -Recurse
          Compress-Archive -Path build/windows/release_zip/* -DestinationPath build/flutter_windows_app.zip

      # 8. 上传到 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
