name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 仅在 push tag 时触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: |
          flutter clean
          flutter build windows --release

      - name: Find Windows exe
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path build/windows -Recurse -Filter *.exe | Select-Object -First 1
          if (-not $exe) {
            Write-Error "No exe found. Build might have failed."
            exit 1
          }
          echo "Found exe at $($exe.FullName)"
          echo "exe_path=$($exe.FullName)" >> $GITHUB_OUTPUT

      - name: Create zip
        run: |
          $zipDir = "build/windows/release_zip"
          mkdir $zipDir
          Copy-Item -Path ${{ steps.find_exe.outputs.exe_path }} -Destination $zipDir
          Compress-Archive -Path "$zipDir/*" -DestinationPath "build/flutter_windows_app.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
