name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 只有打 tag 才触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"
          architecture: x64

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Check build output
        run: dir build/windows -Recurse

      - name: Zip Windows build
        shell: powershell
        run: |
          $srcPath = "build/windows/runner/Release"
          if (Test-Path $srcPath) {
            Write-Host "Found build output at $srcPath"
            mkdir build/windows/release_zip
            Copy-Item -Path "$srcPath/*" -Destination build/windows/release_zip -Recurse
            Compress-Archive -Path build/windows/release_zip/* -DestinationPath build/flutter_windows_app.zip
            Write-Host "Zip created at build/flutter_windows_app.zip"
          } else {
            Write-Error "$srcPath does not exist. Build might have failed."
            exit 1
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/flutter_windows_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
