name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # 只在打版本 tag 时触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. 获取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"
          architecture: x64

      # 3. 启用 Windows Desktop
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # 4. 获取依赖
      - name: Get dependencies
        run: flutter pub get

      # 5. 构建 Windows Release
      - name: Build Windows Release
        run: flutter build windows --release

      # 6. 压缩 Release 文件夹成 ZIP
      - name: Create ZIP of Release
        run: |
          mkdir build/windows/release_zip
          powershell Compress-Archive -Path build/windows/runner/Release -DestinationPath build/windows/release_zip/${{ github.ref_name }}.zip

      # 7. 上传 ZIP 到 GitHub Release
      - name: Create GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/windows/release_zip/${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
